### ISSUE TITLE
ConfigFactory Not Found

### ISSUE THREAD

**Issue by SLYJason** [cep21/circuit#106]
Hi, the [Hystrix Configuration Readme](https://github.com/cep21/circuit#hystrix-configuration) said can use `hystrix.ConfigFactory` to config the opene/closer, but I did not find `ConfigFactory` in this repo. Is this readme out of date?

**Comment by cep21** [comment]
Nice catch!  It's at https://github.com/cep21/circuit/blob/700836dc9a95756136ce20df20ae5d3f3d8b59fd/v3/closers/hystrix/config.go and is called `Factory` not `ConfigFactory`.  I'll update the docs
