### ISSUE TITLE
Retrieve request context data through metrics callback

### ISSUE THREAD

**Issue by aadedamola** [cep21/circuit#108]
## Problem

Contexts can be used to manage information about requests. Some of these request's information may require logging. It will be useful to get these additional information via the original context in the metrics [callbacks]( https://github.com/cep21/circuit/blob/b244db881625d4706bda7961cf2b5f3c8423985f/v3/metrics.go#L164). 

Or is there any other way to go about this?

**Comment by aadedamola** [comment]
The context is being passed in here https://github.com/cep21/circuit/blob/b244db881625d4706bda7961cf2b5f3c8423985f/v3/circuit.go#L259

The idea is to propagate/extend it to the callbacks

**Comment by cep21** [comment]
I agree this is a reasonable idea. Do you have ideas how to do this without breaking backwards compatibility?

**Comment by aadedamola** [comment]
How about introducing additional callbacks that contain the context as one of each callback's parameters?

`type RunMetrics interface {
	Success(context Context, now time.Time, duration time.Duration)`

Perhaps, also adding a boolean flag in the ExecutionConfig `returnContextToCallbacks` to manage which callback is called. https://github.com/cep21/circuit/blob/b244db881625d4706bda7961cf2b5f3c8423985f/v3/config.go#L43

When the manager is initialised with configuration values, we can specify which callbacks we want to use by nature of the flag

**Comment by aadedamola** [comment]
Or we can use any configuration, it doesn't matter.

**Comment by cep21** [comment]
RunMetrics  is a public interface.  If we add methods to it, it will cause people's code to not compile anymore if they have custom structs that implement it.

**Comment by aadedamola** [comment]
Also, do you think the other route is acceptable? Will that be accepted as a valid contribution?

**Comment by cep21** [comment]
Sorry for the delay.  I don't think a new major version is workable.  I think it's best to create a new interface `type RunMetricsCtx interface`, have all the built in stuff implement both, and have calls like `c.CmdMetricCollector.ErrShortCircuit(startTime)` try to cast to a RunMetricsCtx, and if it can, use that instead.

There are still some details to iron out, but I think it can work.  My only concern would be to not hurt the efficiency of the existing code.

**Comment by aadedamola** [comment]
Ah I see, seems like a massive duplication but I think it will work.

**Comment by cep21** [comment]
I think we will probably do this as the v4 library.  Discussing in https://github.com/cep21/circuit/issues/115

Will close as stale since it's been a while and probably won't make it into the current v3
