### ISSUE TITLE
v4 library feedback thread

### ISSUE THREAD

**Issue by cep21** [cep21/circuit#115]
Hi!

I'm thinking about what to modify for the v4 version of the library.  Here is a feedback thread for all to contribute.

Some ideas off the top of my head:

* Remove the "/v3" root directory I needed to support projects that weren't on go modules.  Use git tags instead
* Move statsd implementation to another library (#113 )
* Add ctx to the stats interfaces (#108 )
* Make the "zero" value "off" for configuration, rather than the defaults (See #114 )
* Make a common "circuit check" interface for people to add things like (#34 ) and move all the checks we currently have (concurrency, timeout, etc) into their own interface implementation
* Move benchmarks to their own repo

Do people have other thoughts on things they would change?

**Comment by jxofficial** [comment]
One usecase that I have is to have an option to run the fallback function only once per circuit trip. 

example
```
fallBackFn := func(ctx context.Context, err error) error {
    log("circuit is open")
    return nil
}
```
In the current implementation, the logs will be repeated until the circuit is closed, which can be undesirable.

Currently, It's hard to control how many times the fallback function gets called on the user level because we do not have access to a variable like `FromClosedToOpen` which indicates when the circuit was opened. If we had such a variable, the user of the library could possibly do something like 
```
fallbackFn = nil
if circuit.FromClosedToOpen {
    fallBackFn := func(ctx context.Context, err error) error {
        log("circuit is open")
        return nil
    }
}
```
If this feature will be adopted, I don't mind making a PR for it! (with some assistance, of course)

**Comment by cep21** [comment]
> I managed to implement this on the user-level side

How did you do that?  I'm guessing you inspected the `err` in the fallback func.  I agree having some context during fallback processing would be useful.  We could add that without changing the API by stuffing more information in the `ctx`, but that would slightly hurt the efficiency.

**Comment by jxofficial** [comment]
I made a wrapper over the circuit library; something like this

```
type CircuitBreaker struct {
	circuit                     cep21.Circuit
	maxFallbackCalls  int
	numFallbackCalls  int
	mu                           sync.Mutex
}

func (c *CircuitBreaker) Execute(
    ctx context.Context,
    runFunc func(context.Context) error,
    fallbackFunc func(context.Context, error) error,
) {
c.mu.Lock()
isOpen := c.circuit.IsOpen()
if isOpen {
    c.numFallbackCalls++
    if c.numFallbackCalls > c.maxFallbackCalls {
        // make the fallback func do nothing
        fallbackFunc = func(context.Context, error) error {
	    return nil
	}
    }
} else {
    // circuit is closed - reset for the next time the circuit trips
    if c.numFallbackCalls > 0 {
        c.circuitOpenNumFallbackCalls = 0
    }
}
c.mu.Unlock()
return c.circuit.Execute(ctx, runFunc, fallbackFunc)
}
```
It's not the cleanest way, and I'm not even sure if it's _correct_, but that's the best I could come up with.

**Comment by cep21** [comment]
Adding another thing to the v4 list:
* Drop support for Gopkg.toml

**Comment by cep21** [comment]
I will work on v4 now.  A development draft will continue to be pushed to https://github.com/cep21/circuit/pull/121 until it's ready to merge.

**Comment by cep21** [comment]
I believe #121 is very close to ready to merge.  If anyone is curious, please review and try using it.  I'll wait a week or so before fully pushing and upgrading to v4: incase someone has suggestions.

**Comment by cep21** [comment]
v4 has been released.  Please raise any issues or concerns you have.
