### ISSUE TITLE
Manager.GetCircuit should work on an empty manager

### ISSUE THREAD

**Issue by cep21** [cep21/circuit#38]
On an empty manager object, it should return nil

**Comment by chrisvaughn** [comment]
I was looking at issues in this repo to contribute to. Either this isn't an issue any longer or this needs more info. There appears to be a test for this:
```
func TestManager_Empty(t *testing.T) {
	h := Manager{}
	if h.GetCircuit("does_not_exist") != nil {
		t.Error("found a circuit that does not exist")
	}
}
```

If I'm misunderstanding the issue and this needs work please let me know.

**Comment by cep21** [comment]
Hmmm perfect!  Thanks for catching this.
