### ISSUE TITLE
execution MaxConcurrentRequests not working right

### ISSUE THREAD

**Issue by wangzz719** [cep21/circuit#51]
In my test, I set MaxConcurrentRequests=4，and I send request concurrent=1K，I find the success request is much more than 4。

**Comment by cep21** [comment]
Do you have a failing test case? We have a test for this and it doesnt seem
to get above MaxConcurrentRequests.

**Comment by wangzz719** [comment]
In my test, the runFunc is used to read data from Redis, and the MaxConcurrentRequests is 4. 

https://github.com/cep21/circuit/blob/master/circuit.go#L276 shows that MaxConcurrentRequests will decrease 1 after runFunc executed. 

I might misunderstand MaxConcurrentRequests. 
If I want there would be only 4 runFunc could be executed in per second no matter how high the request QPS is, what should I do?

**Comment by cep21** [comment]
There is no built in functionality for rate limiting.  MaxConcurrentRequests is about limiting requests at the same time.  These libraries may help for rate limiting.

https://godoc.org/golang.org/x/time/rate
https://github.com/golang/go/wiki/RateLimiting

**Comment by wangzz719** [comment]
I will have a try. Thanks a lot.
