### ISSUE TITLE
benchmark source file is gone

### ISSUE THREAD

**Issue by jiacai2050** [cep21/circuit#79]
In readme, https://github.com/cep21/circuit/blob/master/benchmarking/benchmark_hystrix_test.go is gone

**Comment by cep21** [comment]
Good catch!  It was moved to https://github.com/cep21/circuit/blob/master/v3/benchmarking/benchmark_hystrix_test.go in the migration to modules. I'll update.

**Comment by cep21** [comment]
Resolved in https://github.com/cep21/circuit/commit/683d4caf57bc056218f390a3a15b9c51c184e494
