### ISSUE TITLE
example config error

### ISSUE THREAD

**Issue by daliny** [cep21/circuit#80]
at `https://github.com/cep21/circuit/blob/v3.1.0/v3/example/main.go#L81`

`circuit.Config{}` should be configured, like  
```
circuit.Config{
General: circuit.GeneralConfig{
	OpenToClosedFactory: hystrix.CloserFactory(hystrix.ConfigureCloser{}),
	ClosedToOpenFactory: hystrix.OpenerFactory(hystrix.ConfigureOpener{}),
}
```
right?

**Comment by cep21** [comment]
Hi,

That looks correct.  I haven't touched the examples in a long time.
