### ISSUE TITLE
Custom errors

### ISSUE THREAD

**Issue by sharadbhat** [cep21/circuit#86]
Hi, can we pass custom errors as failures of the circuit?

From what I understood, we can return error from the `Execute` method. But it isn't considered as a failure of the circuit. I wanted to find out if it was possible to do so. 

Thanks in advance!

**Comment by sharadbhat** [comment]
I figured it out.

For anyone wondering, an error returned by the inner function in `Execute` is considered an error of the circuit unless `SimpleBadRequest` is used.

Correct me if I'm wrong.

**Comment by cep21** [comment]
That is correct.  I try to clarify it a bit on the godoc of `Execute`

```
// Execute the circuit.  Prefer this over Go.  Similar to http://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/HystrixCommand.html#execute--
// The returned error will either be the result of runFunc, the result of fallbackFunc, or an internal library error.
// Internal library errors will match the interface Error and you can use type casting to check this.
```
